name = "figma-component-health-ent"
main = "unified-worker-working.js"
compatibility_date = "2024-01-15"

[vars]
NODE_ENV = "production"

# Serve frontend assets from dist directory
[assets]
directory = "./dist"